	PROGRAM PDB2CUBE
	IMPLICIT REAL*8 (A-H,O-Z)
	PARAMETER(MAXATOMS=500)
	CHARACTER*6 DUMMY6
	CHARACTER*4 DUMMY4
	CHARACTER*2 ATOM(MAXATOMS)
	character*2 GROUP,DUMMY2
	INTEGER iDUMMY, IMOL, IA(MAXATOMS)
	REAL*8 X(MAXATOMS,3)
      real*8 :: BohrtoAng=0.529177249

9	format(A6,I5,1x,A2,A2,A4,A2,I4,A4,3F8.3,2f6.2,10X,A2,2X)  

	I=1
	OPEN(11,FILE='1car6bchl.pdb',status='old')
10	READ(11,9,END=50)DUMMY6,ITEMP,ATOM(I),DUMMY2,DUMMY4,GROUP,
     .     IMOL,DUMMY4,X(i,1),X(I,2),X(I,3)!, TEMP,TEMP,ATOM(I)
c	write(*,9)DUMMY6,ITEMP,ATOM(I),DUMMY2,DUMMY4,GROUP,
c     .     IMOL,DUMMY4,X(i,1),X(I,2),X(I,3)!, TEMP,TEMP,ATOM(I)
	I=I+1
	GOTO 10
50	CONTINUE
	NATOMS=I-1
	CLOSE(11)
C CHANGE THE UNITS FROM ANGSTROM TO BOHR
	DO I=1,NATOMS
	  DO J=1,3
	    X(I,J) = X(I,J)/BOHRTOANG
	  ENDDO
	ENDDO
C ASSIGN ATOMIC NUMBERS
	DO I=1,NATOMS
	  IF (ATOM(I).EQ.'MG') THEN
	     IA(I)=12
	  ELSEIF (ATOM(I).EQ.' C') THEN
	     IA(I)=6
	  ELSEIF (ATOM(I).EQ.' H') THEN
	     IA(I)=1
	  ELSEIF (ATOM(I).EQ.' O') THEN
	     IA(I)=8
	  ELSEIF (ATOM(I).EQ.' N') THEN
	     IA(I)=7
	  ELSE
	     IA(I)=99
	  ENDIF
	ENDDO
	
	ZERO=0.0
	ONE=1.0
	IZERO=0
	WRITE(*,*)'1 RG+6 BCHL'
	WRITE(*,*)'directly from cube file'

	WRITE(*,9000)NATOMS, ZERO,ZERO,ZERO
	WRITE(*,9000)IZERO, ONE,ZERO,ZERO
	WRITE(*,9000)IZERO, ZERO, ONE,ZERO
	WRITE(*,9000)IZERO, ZERO,ZERO,ONE
	DO I=1,NATOMS
	  WRITE(*,9000) IA(I), REAL(IA(I)), X(I,1),X(I,2),X(I,3)
	ENDDO
 9000 FORMAT(I5, 4F12.6)
	
	END